### ISSUE TITLE
dependency install error

### ISSUE THREAD

**Issue by jancborchardt** [talkatv/talkatv#17]
When trying to install the dependencies, I get some errors:

``` bash
user@Rechenknecht:~/talkatv$ python setup.py develop

[…]

Installed /home/user/talkatv
Processing dependencies for talkatv==0.0.1.dev
Searching for py-bcrypt
Reading http://pypi.python.org/simple/py-bcrypt/
Reading http://www.mindrot.org/py-bcrypt.html
Best match: py-bcrypt 0.2
Downloading http://www.mindrot.org/files/py-bcrypt/py-bcrypt-0.2.tar.gz
Processing py-bcrypt-0.2.tar.gz
Running py-bcrypt-0.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-B4mKrh/py-bcrypt-0.2/egg-dist-tmp-cqwXK8
bcrypt/bcrypt_python.c:17:20: fatal error: Python.h: No such file or directory
compilation terminated.
error: Setup script exited with error: command 'gcc' failed with exit status 1
```

And trying to run the site also gives other errors, probably because the earlier one failed:

``` bash
user@Rechenknecht:~/talkatv$ python run.py 
Traceback (most recent call last):
  File "run.py", line 20, in <module>
    from talkatv import app
  File "/home/user/talkatv/talkatv/__init__.py", line 19, in <module>
    from flask import Flask
ImportError: No module named flask
```

**Comment by joar** [comment]
`sudo apt-get install python-dev` will solve the first issue at least.

**Comment by jancborchardt** [comment]
Yeah, thanks! Earlier I also needed to:

sudo apt-get install python-dev python-virtualenv
pip install Flask sqlalchemy wtforms

Added that to the readme in my fork, will pull request as soon as I put the logo in.
